# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 01:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=70)),
                ('sign', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('image_id', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_butur', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('wind_direction', models.CharField(blank=True, max_length=10)),
                ('wind_max', models.DecimalField(decimal_places=0, max_digits=3)),
                ('temp', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sky', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('road', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cond.Road')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cond.Road'),
        ),
        migrations.AddField(
            model_name='condition',
            name='road',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cond.Road'),
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('road', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cond.Weather')),
                ('name', models.CharField(max_length=200)),
                ('wind', models.SmallIntegerField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=10)),
                ('wind_max', models.DecimalField(decimal_places=0, max_digits=3)),
                ('temp', models.DecimalField(decimal_places=0, max_digits=3)),
                ('temp_road', models.DecimalField(decimal_places=0, max_digits=3)),
                ('humidity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cond.Weather'),
        ),
    ]
