# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Last Update'),
            preserve_default=False,
        ),
    ]
