# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecast',
            name='wind_max',
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='wind',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
