# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0002_road_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='last_update',
            field=models.DateTimeField(verbose_name='Last Update'),
        ),
    ]
