# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0002_auto_20170729_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherforecast',
            name='time',
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='hour',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
