# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0003_auto_20170527_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wind', models.SmallIntegerField()),
                ('wind_direction', models.CharField(max_length=10)),
                ('wind_max', models.CharField(max_length=10)),
                ('temp', models.IntegerField()),
                ('temp_road', models.SmallIntegerField()),
                ('humidity', models.SmallIntegerField()),
            ],
        ),
    ]
