# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0004_condition_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='sign_string',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
