# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0005_auto_20170605_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='wind_max',
            field=models.SmallIntegerField(),
        ),
    ]
