# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0006_auto_20170605_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update'),
            preserve_default=False,
        ),
    ]
