# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0007_weatherstation_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='humidity',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='temp',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='temp_road',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='wind',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='wind_direction',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='wind_max',
            field=models.CharField(max_length=8),
        ),
    ]
