# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0011_auto_20170606_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='Time of update')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cond.Road')),
            ],
        ),
    ]
